# Generated by Django 4.1.7 on 2023-05-15 16:58

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_submission_updated_at_submittedeye_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='practioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.practioner'),
        ),
        migrations.AlterField(
            model_name='submittedeye',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='submittedeye',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.submission'),
        ),
    ]
