# Generated by Django 4.1.7 on 2023-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_submission_patient_alter_submission_practioner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='submittedeye',
            name='risk_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
