# Generated by Django 4.1.7 on 2023-05-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_submission_risk_level_submittedeye_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedeye',
            name='risk_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
