# Generated by Django 4.1.7 on 2023-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_submittedeye_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
