databases:
  - name: eyeopener
    databaseName: eyeopener
    user: sensvue

services:
  - type: web
    name: eyeopener
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn eyeopener.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eyeopener
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4